#!/usr/bin/env python3
"""Generate multi-window, multi-burn-rate SLO alert rules (Google SRE Workbook).

One definition, two profiles:
  prod  real windows (5m ... 3d): what you would deploy, and what the unit tests cover
  lab   the same shapes with every window divided by ~30, so a live drill can fire
        the alert in a couple of minutes instead of an hour

Usage: gen-slo-rules.py --profile prod|lab [--slo 0.995] > rules.yml
"""
import argparse

# logical window -> real window per profile
WINDOWS = {
    "5m": {"prod": "5m", "lab": "15s"},
    "30m": {"prod": "30m", "lab": "1m"},
    "1h": {"prod": "1h", "lab": "2m"},
    "2h": {"prod": "2h", "lab": "4m"},
    "6h": {"prod": "6h", "lab": "12m"},
    "1d": {"prod": "1d", "lab": "48m"},
    "3d": {"prod": "3d", "lab": "144m"},
}
FOR = {"prod": "2m", "lab": "5s"}
LATENCY_WINDOW = {"prod": "5m", "lab": "30s"}

# name, burn rate, long window, short window, severity, meaning
BURN_ALERTS = [
    ("SLOFastBurn", 14.4, "1h", "5m", "page", "2% of a 30-day budget gone in 1 hour"),
    ("SLOSlowBurn", 6, "6h", "30m", "page", "5% of a 30-day budget gone in 6 hours"),
    ("SLOBudgetBurnTicket", 3, "1d", "2h", "ticket", "10% of a 30-day budget gone in 1 day"),
    ("SLOBudgetLeak", 1, "3d", "6h", "ticket", "budget on track to run out exactly at the end of the window"),
]
RUNBOOK = "https://github.com/aryankasraee/sre-observability/blob/HEAD/runbooks"


def ratio(w):
    return f"slo:http_error_ratio:rate{w}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", choices=["prod", "lab"], required=True)
    ap.add_argument("--slo", type=float, default=0.995)
    a = ap.parse_args()
    budget = round(1 - a.slo, 6)
    real = {k: v[a.profile] for k, v in WINDOWS.items()}

    out = ["# GENERATED by scripts/gen-slo-rules.py --profile %s --slo %s. Do not edit." % (a.profile, a.slo),
           "groups:", "  - name: slo-recording", "    rules:"]
    for logical, w in real.items():
        out += [
            f"      - record: {ratio(logical)}",
            f'        expr: (sum(rate(http_requests_total{{code=~"5.."}}[{w}])) or vector(0)) / sum(rate(http_requests_total[{w}]))',
        ]
    out += ["  - name: slo-alerts", "    rules:"]
    for name, burn, long_w, short_w, sev, meaning in BURN_ALERTS:
        thr = round(burn * budget, 6)
        out += [
            f"      - alert: {name}",
            f"        expr: {ratio(long_w)} > {thr} and {ratio(short_w)} > {thr}",
            f"        for: {FOR[a.profile]}",
            "        labels:",
            f"          severity: {sev}",
            "          slo: availability",
            "          service: shop-api",
            "        annotations:",
            f'          summary: "Burning error budget at {burn}x or faster ({long_w} and {short_w} windows): {meaning}"',
            f'          runbook_url: "{RUNBOOK}/slo-burn.md"',
        ]
    out += [
        "      - alert: HighLatencyP95",
        '        expr: histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[%s]))) > 0.5' % LATENCY_WINDOW[a.profile],
        f"        for: {FOR[a.profile]}",
        "        labels:",
        "          severity: ticket",
        "          service: shop-api",
        "        annotations:",
        '          summary: "p95 latency above 500ms"',
        f'          runbook_url: "{RUNBOOK}/high-latency.md"',
    ]
    print("\n".join(out))


if __name__ == "__main__":
    main()
